#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, RGLDiDocType) {
  RGLDiDocTypeNotDefined = 0,
  RGLDiDocTypePassport = 11,
  RGLDiDocTypeIdentityCard = 12,
  RGLDiDocTypeDiplomaticPassport = 13,
  RGLDiDocTypeServicePassport = 14,
  RGLDiDocTypeSeamansIdentityDocument = 15,
  RGLDiDocTypeIdentityCardforResidence = 16,
  RGLDiDocTypeTraveldocument = 17,
  RGLDiDocTypeOther = 99,
  RGLDiDocTypeVisaID2 = 29,
  RGLDiDocTypeVisaID3 = 30,
  RGLDiDocTypeRegistrationCertificate = 31,
  RGLDiDocTypeNationalIdentityCard = 20,
  RGLDiDocTypeSocialIdentityCard = 21,
  RGLDiDocTypeAliensIdentityCard = 22,
  RGLDiDocTypePrivilegedIdentityCard = 23,
  RGLDiDocTypeResidencePermitIdentityCard = 24,
  RGLDiDocTypeOriginCard = 25,
  RGLDiDocTypeEmergencyPassport = 26,
  RGLDiDocTypeAliensPassport = 27,
  RGLDiDocTypeAlternativeIdentityCard = 28,
  RGLDiDocTypeAuthorizationCard = 32,
  RGLDiDocTypeBeginnerPermit = 33,
  RGLDiDocTypeBorderCrossingCard = 34,
  RGLDiDocTypeChauffeurLicense = 35,
  RGLDiDocTypeChauffeurLicenseUnder18 = 36,
  RGLDiDocTypeChauffeurLicenseUnder21 = 37,
  RGLDiDocTypeCommercialDrivingLicense = 38,
  RGLDiDocTypeCommercialDrivingLicenseIndtuctionalPermit = 39,
  RGLDiDocTypeCommercialDrivingLicenseUnder18 = 40,
  RGLDiDocTypeCommercialDrivingLicenseUnder21 = 41,
  RGLDiDocTypeCommercialIndtuctionPermit = 42,
  RGLDiDocTypeCommercialNewPermit = 43,
  RGLDiDocTypeConcealedCarryLicense = 44,
  RGLDiDocTypeConcealedFirearmPermit = 45,
  RGLDiDocTypeConditionalDrivingLicense = 46,
  RGLDiDocTypeDepartmentOfVeteransAffairsIdentityCard = 47,
  RGLDiDocTypeDiplomaticDrivingLicense = 48,
  RGLDiDocTypeDrivingLicense = 49,
  RGLDiDocTypeDrivingLicenseIndtuctionalPermit = 50,
  RGLDiDocTypeDrivingLicenseIndtuctionalPermitUnder18 = 51,
  RGLDiDocTypeDrivingLicenseIndtuctionalPermitUnder21 = 52,
  RGLDiDocTypeDrivingLicenseLearnersPermit = 53,
  RGLDiDocTypeDrivingLicenseLearnersPermitUnder18 = 54,
  RGLDiDocTypeDrivingLicenseLearnersPermitUnder21 = 55,
  RGLDiDocTypeDrivingLicenseNovice = 56,
  RGLDiDocTypeDrivingLicenseNoviceUnder18 = 57,
  RGLDiDocTypeDrivingLicenseNoviceUnder21 = 58,
  RGLDiDocTypeDrivingLicenseRegisteredOffender = 59,
  RGLDiDocTypeDrivingLicenseRedtictedUnder18 = 60,
  RGLDiDocTypeDrivingLicenseRedtictedUnder21 = 61,
  RGLDiDocTypeDrivingLicenseTemporaryVisitor = 62,
  RGLDiDocTypeDrivingLicenseTemporaryVisitorUnder18 = 63,
  RGLDiDocTypeDrivingLicenseTemporaryVisitorUnder21 = 64,
  RGLDiDocTypeDrivingLicenseUnder18 = 65,
  RGLDiDocTypeDrivingLicenseUnder21 = 66,
  RGLDiDocTypeEmploymentDrivingPermit = 67,
  RGLDiDocTypeEnhancedChauffeurLicense = 68,
  RGLDiDocTypeEnhancedChauffeurLicenseUnder18 = 69,
  RGLDiDocTypeEnhancedChauffeurLicenseUnder21 = 70,
  RGLDiDocTypeEnhancedCommercialDrivingLicense = 71,
  RGLDiDocTypeEnhancedDrivingLicense = 72,
  RGLDiDocTypeEnhancedDrivingLicenseUnder18 = 73,
  RGLDiDocTypeEnhancedDrivingLicenseUnder21 = 74,
  RGLDiDocTypeEnhancedIdentityCard = 75,
  RGLDiDocTypeEnhancedIdentityCardUnder18 = 76,
  RGLDiDocTypeEnhancedIdentityCardUnder21 = 77,
  RGLDiDocTypeEnhancedOperatorsLicense = 78,
  RGLDiDocTypeFirearmsPermit = 79,
  RGLDiDocTypeFullProvisionalLicense = 80,
  RGLDiDocTypeFullProvisionalLicenseUnder18 = 81,
  RGLDiDocTypeFullProvisionalLicenseUnder21 = 82,
  RGLDiDocTypeGenevaConventionsIdentityCard = 83,
  RGLDiDocTypeGraduatedDrivingLicenseUnder18 = 84,
  RGLDiDocTypeGraduatedDrivingLicenseUnder21 = 85,
  RGLDiDocTypeGraduatedIndtuctionPermitUnder18 = 86,
  RGLDiDocTypeGraduatedIndtuctionPermitUnder21 = 87,
  RGLDiDocTypeGraduatedLicenseUnder18 = 88,
  RGLDiDocTypeGraduatedLicenseUnder21 = 89,
  RGLDiDocTypeHandgunCarryPermit = 90,
  RGLDiDocTypeIdentityAndPrivilegeCard = 91,
  RGLDiDocTypeIdentityCardMobilityImpaired = 92,
  RGLDiDocTypeIdentityCardRegisteredOffender = 93,
  RGLDiDocTypeIdentityCardTemporaryVisitor = 94,
  RGLDiDocTypeIdentityCardTemporaryVisitorUnder18 = 95,
  RGLDiDocTypeIdentityCardTemporaryVisitorUnder21 = 96,
  RGLDiDocTypeIdentityCardUnder18 = 97,
  RGLDiDocTypeIdentityCardUnder21 = 98,
  RGLDiDocTypeIgnitionInterlockPermit = 100,
  RGLDiDocTypeImmigrantVisa = 101,
  RGLDiDocTypeIndtuctionPermit = 102,
  RGLDiDocTypeIndtuctionPermitUnder18 = 103,
  RGLDiDocTypeIndtuctionPermitUnder21 = 104,
  RGLDiDocTypeInterimDrivingLicense = 105,
  RGLDiDocTypeInterimIdentityCard = 106,
  RGLDiDocTypeIntermediateDrivingLicense = 107,
  RGLDiDocTypeIntermediateDrivingLicenseUnder18 = 108,
  RGLDiDocTypeIntermediateDrivingLicenseUnder21 = 109,
  RGLDiDocTypeJuniorDrivingLicense = 110,
  RGLDiDocTypeLearnerIndtuctionalPermit = 111,
  RGLDiDocTypeLearnerLicense = 112,
  RGLDiDocTypeLearnerLicenseUnder18 = 113,
  RGLDiDocTypeLearnerLicenseUnder21 = 114,
  RGLDiDocTypeLearnerPermit = 115,
  RGLDiDocTypeLearnerPermitUnder18 = 116,
  RGLDiDocTypeLearnerPermitUnder21 = 117,
  RGLDiDocTypeLimitedLicense = 118,
  RGLDiDocTypeLimitedPermit = 119,
  RGLDiDocTypeLimitedTermDrivingLicense = 120,
  RGLDiDocTypeLimitedTermIdentityCard = 121,
  RGLDiDocTypeLiquorIdentityCard = 122,
  RGLDiDocTypeNewPermit = 123,
  RGLDiDocTypeNewPermitUnder18 = 124,
  RGLDiDocTypeNewPermitUnder21 = 125,
  RGLDiDocTypeNonUsCitizenDrivingLicense = 126,
  RGLDiDocTypeOccupationalDrivingLicense = 127,
  RGLDiDocTypeOneidaTribeOfIndiansIdentityCard = 128,
  RGLDiDocTypeOperatorLicense = 129,
  RGLDiDocTypeOperatorLicenseUnder18 = 130,
  RGLDiDocTypeOperatorLicenseUnder21 = 131,
  RGLDiDocTypePermanentDrivingLicense = 132,
  RGLDiDocTypePermitToReEnter = 133,
  RGLDiDocTypeProbationaryAutoLicense = 134,
  RGLDiDocTypeProbationaryDrivingLicenseUnder18 = 135,
  RGLDiDocTypeProbationaryDrivingLicenseUnder21 = 136,
  RGLDiDocTypeProbationaryVehicleSalespersonLicense = 137,
  RGLDiDocTypeProvisionalDrivingLicense = 138,
  RGLDiDocTypeProvisionalDrivingLicenseUnder18 = 139,
  RGLDiDocTypeProvisionalDrivingLicenseUnder21 = 140,
  RGLDiDocTypeProvisionalLicense = 141,
  RGLDiDocTypeProvisionalLicenseUnder18 = 142,
  RGLDiDocTypeProvisionalLicenseUnder21 = 143,
  RGLDiDocTypePublicPassengerChauffeurLicense = 144,
  RGLDiDocTypeRacingAndGamingComissionCard = 145,
  RGLDiDocTypeRefugeeTravelDocument = 146,
  RGLDiDocTypeRenewalPermit = 147,
  RGLDiDocTypeRedtictedCommercialDrivingLicense = 148,
  RGLDiDocTypeRedtictedDrivingLicense = 149,
  RGLDiDocTypeRedtictedPermit = 150,
  RGLDiDocTypeSeasonalPermit = 151,
  RGLDiDocTypeSeasonalResidentIdentityCard = 152,
  RGLDiDocTypeSeniorCitizenIdentityCard = 153,
  RGLDiDocTypeSexOffender = 154,
  RGLDiDocTypeSocialSecurityCard = 155,
  RGLDiDocTypeTemporaryDrivingLicense = 156,
  RGLDiDocTypeTemporaryDrivingLicenseUnder18 = 157,
  RGLDiDocTypeTemporaryDrivingLicenseUnder21 = 158,
  RGLDiDocTypeTemporaryIdentityCard = 159,
  RGLDiDocTypeTemporaryIndtuctionPermitIdentityCard = 160,
  RGLDiDocTypeTemporaryIndtuctionPermitIdentityCardUnder18 = 161,
  RGLDiDocTypeTemporaryIndtuctionPermitIdentityCardUnder21 = 162,
  RGLDiDocTypeTemporaryVisitorDrivingLicense = 163,
  RGLDiDocTypeTemporaryVisitorDrivingLicenseUnder18 = 164,
  RGLDiDocTypeTemporaryVisitorDrivingLicenseUnder21 = 165,
  RGLDiDocTypeUniformedServicesIdentityCard = 166,
  RGLDiDocTypeVehicleSalespersonLicense = 167,
  RGLDiDocTypeWorkerIdentificationCredential = 168,
  RGLDiDocTypeCommercialDrivingLicenseNovice = 169,
  RGLDiDocTypeCommercialDrivingLicenseNoviceUnder18 = 170,
  RGLDiDocTypeCommercialDrivingLicenseNoviceUnder21 = 171,
  RGLDiDocTypePassportCard = 172,
  RGLDiDocTypePermanentResidentCard = 173,
  RGLDiDocTypePersonalIdentificationVerification = 174,
  RGLDiDocTypeTemporaryOperatorLicense = 175,
  RGLDiDocTypeDrivingLicenseUnder19 = 176,
  RGLDiDocTypeIdentityCardUnder19 = 177,
  RGLDiDocTypeVisa = 178,
  RGLDiDocTypeTemporaryPassport = 179,
  RGLDiDocTypeVotingCard = 180,
  RGLDiDocTypeHealthCard = 181,
  RGLDiDocTypeCertificateOfCitizenship = 182,
  RGLDiDocTypeAddressCard = 183,
  RGLDiDocTypeAirportImmigrationCard = 184,
  RGLDiDocTypeAlienRegidtationCard = 185,
  RGLDiDocTypeAPEHCard = 186,
  RGLDiDocTypeCoupontoDrivingLicense = 187,
  RGLDiDocTypeCrewMemberCertificate = 188,
  RGLDiDocTypeDocumentForReturn = 189,
  RGLDiDocTypeECard = 190,
  RGLDiDocTypeEmploymentCard = 191,
  RGLDiDocTypeHKSARImmigrationForm = 192,
  RGLDiDocTypeImmigrantcard = 193,
  RGLDiDocTypeLabourCard = 194,
  RGLDiDocTypeLaissezPasser = 195,
  RGLDiDocTypeLawyerIdentityCertificate = 196,
  RGLDiDocTypeLicenseCard = 197,
  RGLDiDocTypePassportStateless = 198,
  RGLDiDocTypePassportChild = 199,
  RGLDiDocTypePassportConsular = 200,
  RGLDiDocTypePassportDiplomaticService = 201,
  RGLDiDocTypePassportOfficial = 202,
  RGLDiDocTypePassportProvisional = 203,
  RGLDiDocTypePassportSpecial = 204,
  RGLDiDocTypePermissiontotheLocalBorderTraffic = 205,
  RGLDiDocTypeSEDESOLCard = 207,
  RGLDiDocTypeSocialCard = 208,
  RGLDiDocTypeTBCard = 209,
  RGLDiDocTypeVehiclePassport = 210,
  RGLDiDocTypeWDocument = 211,
  RGLDiDocTypeDiplomaticIdentityCard = 212,
  RGLDiDocTypeConsularIdentityCard = 213,
  RGLDiDocTypeIncomeTaxCard = 214,
  RGLDiDocTypeResidencePermit = 215,
  RGLDiDocTypeDocumentOfIdentity = 216,
  RGLDiDocTypeBorderCrossingPermit = 217,
  RGLDiDocTypePassportLimitedValidity = 218,
  RGLDiDocTypeSIMCard = 219,
  RGLDiDocTypeTaxCard = 220,
  RGLDiDocTypeCompanyCard = 221,
  RGLDiDocTypeDomesticPassport = 222,
  RGLDiDocTypeIdentityCertificate = 223,
  RGLDiDocTypeResidentIdCard = 224,
  RGLDiDocTypeArmedForcesIdentityCard = 225,
  RGLDiDocTypeProfessionalCard = 226,
  RGLDiDocTypeRegistrationStamp = 227,
  RGLDiDocTypeDriverCard = 228,
  RGLDiDocTypeDriverTrainingCertificate = 229,
  RGLDiDocTypeQualificationDrivingLicense = 230,
  RGLDiDocTypeMembershipCard = 231,
  RGLDiDocTypePublicVehicleDriverAuthorityCard = 232,
  RGLDiDocTypeMarineLicense = 233,
  RGLDiDocTypeTemporaryLearnerDrivingLicense = 234,
  RGLDiDocTypeTemporaryCommercialDrivingLicense = 235,
  RGLDiDocTypeInterimInstructionalPermit = 236,
  RGLDiDocTypeCertificateOfCompetency = 237,
  RGLDiDocTypeCertificateOfProficiency = 238,
} NS_SWIFT_NAME(DiDocType);

typedef NS_ENUM(NSInteger, RGLDocFormat) {
  RGLDocFormatID1        = 0,
  RGLDocFormatID2        = 1,
  RGLDocFormatID3        = 2,
  RGLDocFormatID3_x2     = 5,
  RGLDocFormatCustom    = 1000,
  RGLDocFormatFlexible  = 1002
} NS_SWIFT_NAME(DocFormat);

NS_SWIFT_NAME(DocumentReaderDocumentType)
@interface RGLDocumentReaderDocumentType : NSObject

@property(nonatomic, strong, readonly, nullable) NSString *name;
@property(nonatomic, assign, readonly) NSInteger documentID;
@property(nonatomic, strong, readonly, nullable) NSString *ICAOCode;
@property(nonatomic, strong, readonly, nonnull) NSArray<NSNumber *> *FDSID;
@property(nonatomic, assign, readonly) RGLDiDocType dType;
@property(nonatomic, assign, readonly) RGLDocFormat dFormat;
@property(nonatomic, assign, readonly) BOOL dMRZ;
@property(nonatomic, strong, readonly, nullable) NSString *dDescription;
@property(nonatomic, strong, readonly, nullable) NSString *dYear;
@property(nonatomic, strong, readonly, nullable) NSString *dCountryName;
@property(nonatomic, assign, readonly) NSInteger pageIndex;

- (instancetype _Nonnull)initWithJSON:(NSDictionary *_Nonnull)json;
+ (instancetype _Nonnull)initWithJSON:(NSDictionary * _Nonnull)json;
- (NSDictionary *_Nonnull)jsonDictionary;

@end
