#import <Foundation/Foundation.h>

FOUNDATION_EXPORT NSString *const RGL_SCENARIO_MRZ;
FOUNDATION_EXPORT NSString *const RGL_SCENARIO_BARCODE;
FOUNDATION_EXPORT NSString *const RGL_SCENARIO_LOCATE;
FOUNDATION_EXPORT NSString *const RGL_SCENARIO_OCR;
FOUNDATION_EXPORT NSString *const RGL_SCENARIO_DOCTYPE;
FOUNDATION_EXPORT NSString *const RGL_SCENARIO_MRZ_OR_BARCODE;
FOUNDATION_EXPORT NSString *const RGL_SCENARIO_MRZ_OR_LOCATE;
FOUNDATION_EXPORT NSString *const RGL_SCENARIO_MRZ_AND_LOCATE;
FOUNDATION_EXPORT NSString *const RGL_SCENARIO_MRZ_OR_OCR;
FOUNDATION_EXPORT NSString *const RGL_SCENARIO_MRZ_OR_BARCODE_OR_OCR;
FOUNDATION_EXPORT NSString *const RGL_SCENARIO_LOCATE_VISUAL_AND_MRZ_OR_OCR;
FOUNDATION_EXPORT NSString *const RGL_SCENARIO_FULL_PROCESS;
FOUNDATION_EXPORT NSString *const RGL_SCENARIO_FULL_AUTH;
FOUNDATION_EXPORT NSString *const RGL_SCENARIO_ID3RUS;
FOUNDATION_EXPORT NSString *const RGL_SCENARIO_RUS_STAMP;
FOUNDATION_EXPORT NSString *const RGL_SCENARIO_OCR_FREE;
FOUNDATION_EXPORT NSString *const RGL_SCENARIO_CREDIT_CARD;
FOUNDATION_EXPORT NSString *const RGL_SCENARIO_CAPTURE;
