repositories {
    maven { url "https://maven.regulaforensics.com/RegulaDocumentReader" }
    maven { url "https://maven.regulaforensics.com/RegulaDocumentReader/Beta" }
    maven { url "https://maven.regulaforensics.com/RegulaDocumentReader/Nightly" }
    maven { url "https://maven.regulaforensics.com/RegulaDocumentReader/Stage" }
}

dependencies {
    //noinspection GradleDependency
	implementation ('com.regula.documentreader:api:9.9.13492'){
        transitive = true
    }
}
